library(shiny)
library(shinyjs)
library(shinythemes)
library(shinydashboard)

redirectJobHandlerCode <- "Shiny.addCustomMessageHandler('redirectJob', function(jobid) { window.location='?jobid='+jobid; });"

makeFooter <- function() {
  versionstr <- paste0("deepclip-shiny version ", VERSION)
  tagList(
    hr(),
    div(p(class="text-right", versionstr))
  )
}

shinyUI(tagList(
  tags$head(
    tags$script(type="text/javascript", redirectJobHandlerCode),
    tags$link(rel="stylesheet", type="text/css", href="css/style.css")
  ),
  useShinyjs(),
  navbarPage(windowTitle="DeepCLIP", HTML("<a href=\"/\">DeepCLIP</a>"), fluid=FALSE, inverse=FALSE, footer=makeFooter(), theme=shinytheme("yeti"),
    tabPanel("DeepCLIP",
      textOutput("jobStatusText"),
      conditionalPanel("output.jobID == 'NULL'",
        div(class="page-header", h1("Train network")),
        div(class="panel panel-primary",
          div(class="panel-heading", h3(class="panel-title", "Binding sequences")),
          div(class="panel-body",
            p("Select how binding sequences will be provided. If BED file is selected, a target species and assembly must be selected as well."),
            fluidRow(
              column(width=4, selectInput("seqFormat", "File format", c("FASTA file"="fasta", "BED file"="bed"))),
              column(width=4, selectInput("seqAssembly", "Assembly", c("Human (GRCh38/hg38)"="hg38", "Human (GRCh37/hg19)"="hg19", "Mouse (GRCm38/mm10)"="mm10"))),
              column(width=4, fileInput("seqFile", "Sequence file"))
            )
          )
        ),
        div(class="panel panel-primary",
          div(class="panel-heading", h3(class="panel-title", "Background sequences")),
          div(class="panel-body",
            p("Select how background sequences should be generated."),
            tags$ul(
              tags$li("If FASTA file is selected a FASTA file containing sequences must be provided."),
              tags$li("If Generate from BED file is selected sequences will be generated from the provided BED file containing binding sequences."),
              tags$li("If Shuffle input is selected sequences will be generated by reshuffling the provided binding sequences.")
            ),
            fluidRow(
              column(width=4,
                selectInput("bkgSource", "Data source", c("FASTA file"="fasta", "Generate from BED file"="bed", "Shuffle input"="shuffle"))
              ),
              conditionalPanel("input.bkgSource == 'fasta'",
                column(width=4, fileInput("bkgFile", "FASTA file"))
              )
            )
          )
        ),
        div(class="panel panel-primary",
          div(class="panel-heading", h3(class="panel-title", "Parameters")),
          div(class="panel-body",
            p("Data preprocessing:"),
            tags$ul(
              tags$li("Min. sequence length: all sequences shorter than this will be discarded."),
              tags$li("Max. sequence length: all sequences longer than this will be discarded."),
              tags$li("If Pad sequences is given all sequences will be padded with this number of surrounding bases. (BED file only)"),
              tags$li("If Fixed sequence width is given all sequences will be trimmed/padded to fit this length. (BED file only)")
            ),
            fluidRow(
              column(width=3, numericInput("minLength", "Min. sequence length", min=1, max=100, value=1)),
              column(width=3, numericInput("maxLength", "Max. sequence length", min=1, max=100, value=100)),
              column(width=3, numericInput("bedWidth", "Fixed sequence width", min=1, max=100, value=NA)),
              column(width=3, numericInput("bedPadding", "Pad sequences", min=0, max=20, value=NA))
            ),
            sliderInput("epochs", "Training time", min=1, max=10, value=5, step=1, post = " epochs")
          )
        ),
        actionButton("trainButton", "Train network", class="btn-lg btn-primary")
      ),
      conditionalPanel("output.jobStatus == 0",
        div(class="well", style="max-width:600px; margin:auto; text-align:center;",
          h2("Training network"),
          tags$img(src="img/spinner.gif"),
          p("DeepCLIP is currently training your network. This page will automatically redirect once the training is complete."),
          p("You can bookmark this page and come back later.")
        )
      ),
      conditionalPanel("output.jobStatus == 1",
        h1("Evaluate model")
      ),
      conditionalPanel("output.jobStatus == 2",
        div(class="alert alert-danger", "Model training failed"),
        h3("Log"),
        verbatimTextOutput("jobLog")
      )
    ),
    tabPanel("Documentation",
       div(class="page-header", h1("Documentation")),
       includeMarkdown("documentation.md")
    ),
    tabPanel("About",
      div(class="page-header", h1("About")),
      includeMarkdown("about.md")
    )
  )
))