library(shiny)
library(shinyjs)
library(DT)
library(shinyWidgets)

makeFooter <- function() {
  versionstr <- paste0("deepclip-shiny version ", VERSION)
  tagList(
    hr(),
    div(p(class="text-right", versionstr))
  )
}

makeTitledPanel <- function(title, ...) {
  div(class="panel panel-default",
    div(class="panel-heading", h3(class="panel-title", title)),
    div(class="panel-body", ...)
  )
}

shinyUI(tagList(
  includeScript("www/js/redirect.js"),
  includeCSS("www/css/style.css"),
  includeCSS("www/css/loader.css"),
  useShinyjs(),
  div(id="loading-content", h2("Loading..."), div(class="loader", "Loading")),
  navbarPage(windowTitle="DeepCLIP", "DeepCLIP", fluid=FALSE, inverse=TRUE, footer=makeFooter(),
    tabPanel(tagList(icon("window-maximize"), "Dashboard"),
      conditionalPanel("output.jobID == null",
        div(class="page-header", h1("Use pre-trained model")),
        makeTitledPanel("Pre-trained model",
          fluidRow(
            column(width=4, selectInput("pretrainedModel", NULL, NULL, width="100%")),
            column(width=3, actionButton("usePretrainedButton", "Use pre-trained model", class="btn-primary"))
          )
        ),
        div(class="page-header", h1("Train new model")),
        makeTitledPanel("Binding sequences",
          p("Select how binding sequences will be provided. If BED file is selected, a target species and assembly must be selected as well."),
          fluidRow(
            column(width=2,
              radioButtons("seqType", "Sequence type", c("DNA"="DNA", "RNA"="RNA"), inline=TRUE)
            ),
            column(width=3, selectInput("seqFormat", "File format", c("FASTA file"="fasta", "BED file"="bed"))),
            column(width=3, fileInput("seqFile", "Sequence file")),
            conditionalPanel("input.seqFormat == 'bed'",
              column(width=3, selectInput("seqAssembly", "Assembly", REFERENCE_SPECIES))
            )
          )
        ),
        makeTitledPanel("Background sequences",
          p("Select how background sequences should be generated."),
          tags$ul(
            tags$li("If FASTA file is selected a FASTA file containing sequences must be provided."),
            tags$li("If Generate from BED file is selected sequences will be generated from the provided BED file containing binding sequences."),
            tags$li("If Shuffle input is selected sequences will be generated by reshuffling the provided binding sequences.")
          ),
          fluidRow(
            column(width=3,
              selectInput("bkgSource", "Data source", c("FASTA file"="fasta", "Generate from BED file"="bed", "Shuffle input"="shuffle"))
            ),
            conditionalPanel("input.bkgSource == 'fasta'",
              column(width=3, fileInput("bkgFile", "FASTA file"))
            )
          )
        ),
        makeTitledPanel("Sequence preprocessing",
          tags$ul(
            tags$li("Min. sequence length: all sequences shorter than this will be discarded."),
            tags$li("Max. sequence length: all sequences longer than this will be discarded."),
            tags$li("BED file only: If Pad sequences is given all sequences will be padded with this number of surrounding bases."),
            tags$li("BED file only: If Fixed sequence width is given all sequences will be trimmed/padded to fit this length.")
          ),
          
          fluidRow(
            column(width=3, numericInput("minLength", "Min. sequence length", min=1, max=150, value=1)),
            column(width=3, numericInput("maxLength", "Max. sequence length", min=1, max=150, value=75)),
            column(width=3, numericInput("bedWidth", "Fixed sequence width", min=1, max=100, value=NA)),
            column(width=3, numericInput("bedPadding", "Pad sequences", min=0, max=20, value=NA))
          )
        ),
        makeTitledPanel("Data split",
          p("Specify how sequences should be split for training, validation and testing."),
          fluidRow(
            column(width=3, numericInput("trainSplit", "Training (%)", min=1, max=98, value=80, step=1)),
            column(width=3, numericInput("valSplit", "Validation (%)", min=1, max=98, value=10, step=1)),
            column(width=3, numericInput("testSplit", "Testing (%)", min=1, max=98, value=10, step=1))
          )
        ),
        makeTitledPanel("Program control",
          fluidRow(
            column(width=4, sliderInput("epochs", "Training time", min=1, max=25, value=10, step=1, post = " epochs")),
            column(width=3, numericInput("earlyStopping", "Early stopping", min=1, max=25, value=NA, step=1)),
            column(width=3, textInput("randomSeed", "Random seed", value="", placeholder="An integer seed"))
          )
        ),
        actionButton("trainButton", "Train model", class="btn-lg btn-primary")
      ),
      conditionalPanel("output.jobStatus == 0",
        div(class="well", id="trainingProgressBox",
          h2("Training model", class="no-top-margin"),
          uiOutput("jobProgressBar"),
          p("DeepCLIP is currently training your model. This page will automatically redirect once the training is complete."),
          p("You can bookmark this page and come back later.")
        )
      ),
      conditionalPanel("output.jobStatus == 1",
        tabsetPanel(id="model_tabs",
          tabPanel("Summary",
            h2("Model summary"),
            uiOutput("summaryText"),
            fluidRow(
              column(width=5,
                h2("ROC curve"),
                plotOutput("testROCPlot", width=400, height=416)
              ),
              column(width=7,
                h2("CNN filters ranked by score"),
                plotOutput("testPFMLogos", width=600, height=500)
              )
            ),
            h2("Prediction score distribution"),
            plotOutput("testPredDistPlot"),
            downloadButton("downloadSummaryPlots", "Download all plots", class="btn-primary")
          ),
          tabPanel(HTML("Prediction</a></li><li style='float:right'><a id='startOverButton' href='/' class='btn-primary'><i class='fa fa-refresh'></i> Start over"),
            fluidRow(style="margin-top: 20px;",
              column(width=6,
                div(class="panel panel-default",
                  div(class="panel-heading", style="height: 45px", "Sequences"),
                  div(class="panel-body",
                    fileInput("predictSeq", "FASTA file"),
                    textAreaInput("predictSeqText", "Sequences", width="100%")
                  )
                )
              ),
              column(width=6,
                div(class="panel panel-default",
                  div(class="panel-heading", style="height: 45px",
                    materialSwitch("predictPaired", "Predict paired sequences", FALSE, status="primary")
                  ),
                  conditionalPanel("input.predictPaired == true",
                    div(class="panel-body",
                      fileInput("predictSeq2", "FASTA file"),
                      textAreaInput("predictSeqText2", "Sequences", width="100%")
                    )
                  )
                )
              )
            ),
            actionButton("predictButton", "Run prediction", class="btn-lg btn-primary"),
            h3("Predictions"),
            DTOutput("predictionTable"),
            conditionalPanel("typeof(input.predictionTable_rows_selected) != 'undefined' && input.predictionTable_rows_selected.length > 0", 
              plotOutput("predictionProfilePlot", height=300),
              conditionalPanel("input.predictPaired == true",
                materialSwitch("profilePlotDifference", "Plot profile difference (with variants only)", value=FALSE, inline=TRUE, status="primary")
              ),
              downloadButton("downloadPredictionProfilePlot", "Download profile", class="btn-sm")
            )
          )
        )
      ),
      conditionalPanel("output.jobStatus == 2",
        div(class="alert alert-danger", "Model training failed"),
        h3("Log"),
        verbatimTextOutput("jobLog")
      )
    ),
    tabPanel(tagList(icon("book"), "Documentation"),
       div(class="page-header", h1("Documentation")),
       includeMarkdown("documentation.md")
    ),
    tabPanel(tagList(icon("info-circle"), "About"),
      div(class="page-header", h1("About")),
      includeMarkdown("about.md")
    )
  )
))